[package]
name = "example_utils"
version = "0.1.0"
edition = "2024"

[lib]
name = "example_utils"
test = false
bench = false

[dependencies]
defmt = { version = "1.0.1", optional = true }
embassy-executor = { workspace = true }
embassy-net = { workspace = true }
embassy-rp = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
embassy-usb-logger = { workspace = true, optional = true  }
log = { workspace = true, optional = true }

[features]
default = ["log"]
defmt = ["dep:defmt"]
log = ["dep:embassy-usb-logger", "dep:log"]