[workspace]
resolver = "3"
members = [
    "app_with_props",
    "example_secrets",
    "example_utils",
    "graceful_shutdown_using_future_array",
    "graceful_shutdown_using_tasks",
    "hello_world",
    "hello_world_usb_ncm",
    "huge_requests",
    "path_parameters",
    "server_sent_events",
    "set_pico_w_led",
    "various_states",
    "web_sockets"
]
exclude = [
    "hello_world_defmt",
]

[workspace.dependencies]
cortex-m-rt = "0.7.6"
cyw43 = "0.7.0"
cyw43-pio = "0.10.0"
embassy-executor = { version = "0.10.0", features = ["nightly", "platform-cortex-m", "executor-thread"] }
embassy-futures = "0.1.2"
embassy-net = { version = "0.9.1", features = ["icmp-ping-reply", "udp", "tcp", "tcp-listener", "ipv4", "medium-ethernet"] }
embassy-rp = { version = "0.10.0", features = ["critical-section-impl", "time-driver", "rp2040"] }
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
embassy-usb = "0.6.0"
embassy-usb-driver = "0.2.2"
embassy-usb-host = "0.1.0"
embassy-usb-logger = "0.6.0"
heapless = "0.9.3"
log = { version = "0.4.34", default-features = false }
panic-persist = { version = "0.3.0", features = ["utf8"] }
picoserve = { path = "../../picoserve", features = ["embassy", "log"] }
portable-atomic = { version = "1.15.0", features = ["critical-section"], default-features = false }
rand = { version = "0.9.5", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
static_cell = "2.1.1"

# temporary patches to use updated embassy
[patch.crates-io]
cyw43 = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
cyw43-pio = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-net-driver-channel = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-net = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-usb-host = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }
embassy-usb-logger = { git = "https://github.com/embassy-rs/embassy", rev = "7330106" }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"